#!/bin/bash


source ~/.openstackrc
nova list | awk '/hodor/ { print $4}' | xargs nova delete
source ~/.openstackrc-rax2
export OS_REGION_NAME=IAD
nova list | awk '/hodor/ { print $4}' | xargs nova delete

